# Generated by Django 5.0.3 on 2024-09-15 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printapp', '0002_alter_user_is_role_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printjob',
            name='color',
        ),
        migrations.RemoveField(
            model_name='printjob',
            name='copies',
        ),
        migrations.RemoveField(
            model_name='printjob',
            name='pages',
        ),
        migrations.AddField(
            model_name='printjob',
            name='bw_pages',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='printjob',
            name='color_pages',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_role',
            field=models.PositiveIntegerField(choices=[(1, 'Administrator'), (2, 'Moderator'), (3, 'Customer Support Staff')], default=0),
        ),
    ]
