# Generated by Django 5.0.3 on 2024-09-15 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printapp', '0003_remove_printjob_color_remove_printjob_copies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='printjob',
            name='is_payment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='printjob',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_role',
            field=models.PositiveIntegerField(choices=[(3, 'Customer Support Staff'), (2, 'Moderator'), (1, 'Administrator')], default=0),
        ),
    ]
