# Generated by Django 5.0.3 on 2024-09-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printapp', '0004_printjob_is_payment_printjob_modified_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='printjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined'), ('printed', 'Printed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_role',
            field=models.PositiveIntegerField(choices=[(1, 'Administrator'), (2, 'Moderator'), (3, 'Customer Support Staff')], default=0),
        ),
    ]
